package cet.componentMultiMiceManager;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

import org.mt4j.input.inputData.AbstractCursorInputEvt;
import org.mt4j.input.inputData.MTInputEvent;
import org.mt4j.input.inputSources.MultipleMiceInputSource;

import processing.core.PApplet;

import cet.globalMultiMiceManager.CETMultipleMiceManager;

/**
 * Controls which student mice have access to the component, 
 * and whether the students need to work together or take turns.
 * Instructor mouse always have access to the component.
 * 
 * @author Mengdie
 */

public class CETcomponentMultiMiceControl implements ICETMiceChangeListener{
	private CETMultipleMiceManager globalMMmanager;
	private ArrayList<Integer> studentDeviceList;
	private boolean isCollaborative;
	private CETcomponentMultiMiceControlUI ui = null;
	
	protected ArrayList<ActionListener> listenerList;
	
	/**
	 * Floor Control for components
	 * @param m global multiple mice manager
	 */
	public CETcomponentMultiMiceControl( CETMultipleMiceManager m ){
		globalMMmanager = m;
		m.addMultiMiceChangeListener(this);
		studentDeviceList = new ArrayList<Integer>();
		isCollaborative = false;
		listenerList = new ArrayList<ActionListener>();
		addAllStudentDevices();		
	}
	
	public void addStudentDevice( int device ) {
		if( !studentDeviceList.contains(device) && globalMMmanager.getInstructorDevice() != device ) {
			studentDeviceList.add( device );
			fireAction("Student device added.");
		}
	}
	
	public void removeStudentDevice( int device ) {
		int index = studentDeviceList.indexOf(device);
		if( index > -1 ) {
			studentDeviceList.remove( index );
			fireAction("Student device removed.");
		}
	}
	
	public void addAllStudentDevices() {
		studentDeviceList.clear();
		for( int device : globalMMmanager.getDeviceToMouseInfo().keySet() ){
			if( device != globalMMmanager.getInstructorDevice() )
				studentDeviceList.add( device );
		}
		fireAction("Student device added.");
	}
	
	public void removeAllStudentDevices() {
		studentDeviceList.clear();
		fireAction("Student device removed.");
	}
	
	public ArrayList<Integer> getStudentDeviceList(){
		return studentDeviceList;
	}
	
	public boolean isDevicePermitted(int device){
		if( device == globalMMmanager.getInstructorDevice() )
			return true;
		return studentDeviceList.contains(device);
	}
	
	public boolean isCollaborative() {
		return isCollaborative;
	}
	
	public void setCollaborative( boolean is ) {
		isCollaborative = is;
		fireAction("Collaborative mode changed.");
	}
	
	// Multiple mice change events handling
	
	public void deviceConnected(int device) {
		addStudentDevice( device );
		if( ui != null )
			ui.update();
	}
	
	public void deviceDisconnected(int device) {
		removeStudentDevice( device );
		if( ui != null )
			ui.update();
	}

	public void instructorChanged(int device) {
		int instructorDevice = globalMMmanager.getInstructorDevice();
		removeStudentDevice( instructorDevice );
		if( ui != null )
			ui.update();
	}
	
	public void addEventListener( ActionListener l ) {
		listenerList.add(l);
	}
	
	public void removeEventListener( ActionListener l ) {
		listenerList.remove(l);
	}
	
	public ArrayList<ActionListener> getAllEventListeners() {
		return listenerList;
	}
	
	private void fireAction(String command) {
		for( ActionListener l : listenerList )
			l.actionPerformed( new ActionEvent( this, ActionEvent.ACTION_PERFORMED, command) );
	}
	
	/**
	 * Create floor control UI for component
	 * @param x The x-center of the UI icon
	 * @param y The y-center of the UI icon
	 * @param p The MT application
	 * @return
	 */
	public CETcomponentMultiMiceControlUI createUI( int x, int y, PApplet p ){
		ui = new CETcomponentMultiMiceControlUI( x, y, this, p );
		return ui;
	}

	/**
	 * Check if an input event was generated by a mouse with permission to use component
	 * @param event input event
	 * @return
	 */
	public boolean isEventSourcePermitted( MTInputEvent event) {
		return event instanceof AbstractCursorInputEvt
		&& event.getSource() instanceof MultipleMiceInputSource
		&& isDevicePermitted(((MultipleMiceInputSource)event.getSource()).getEventSourceDevice());
	}
}
